language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
script: npm run travis
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $github_token
  keep-history: true
  local-dir: dist/patterns-pedia
