language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github_token:
    secure: LR+oU1DMGRkzks0SvnkwBQWq3rNw6UFuf8CUpDuks024b/GlxfZKuO7B63FJU9K87/TVd9SAYUkPYDzkmX4kdMuIKv3XdI6P/LQXwPXbIl5QtFz9LD4ckVGbjUESg7AQAKsWkzGKpQpcoLuUdrSIJZUMVwu3X3g48wbpN+QIJdjTAt1OUzn6be4MvcjF3/VoozX8qQAin8659f4qDOpSv9DckpKVWswrEBGzkZIbOhB8kfx43rxLqrddY2WUm3DPhxefnGbt97WjLud0EWWB/EDUKNcflqp4zkZ1THvyZIjBnQM6IBCN41r2kC/VyNRsrYT8IWw1OPxUKY5uyfPzKSduARkqdWCBm7kKyXvssbomPPz30DBqDH2PWvJ6c92+QwdhBHlaTmsgWFEbJpN0Sytsh+pz1WL9cIrRf9G9a/5RTokdWDscawhFAHDMjd/Ik3xF8B2ghV2wzNAkEq3t25Azsjb76GwF7Y41hcw9r91iYT5kaQOJzMosZxovqLQtVnv2zPNNMNt+VEHIyPGMlD9/y0HW9wtNkewMOBP0JySX5etZJiXrqjsZqn4+4oMmeDPoKAbBAn3SQ1Y+7A7JHUxcz8mzxR0Rqum+8XXB53Kk5Y5VtprJYQZM7R8U0KEWY+L2FVnpYFGUNhhRx8MXVIzK2B3pX98hCws2QvqzdZ8=
  keep-history: true
  local-dir: dist/pattern-pedia
